export type EncounterStatus='previsit-draft'|'previsit-submitted'|'nurse-intake'|'ready-for-doctor'|'doctor-examining'|'doctor-plan-confirmed'|'nurse-education'|'home-care-active'|'return-visit-due'|'return-visit-checked-in'|'admission-requested'|'inpatient'|'discharge-planning'|'discharged-home';
export type PlanStatus='Draft'|'Doctor confirmed'|'Nurse educated'|'Active at home'|'Superseded'|'Held'|'Completed';
export type TreatmentPlan={planId:string;revision:number;status:PlanStatus;createdBy:'doctor';confirmedAt:string|null;changeSummary:string;medication:{name:string;dose:string;route:string;schedule:string}};
export type AuditEvent={at:string;event:string;actor:'patient'|'nurse'|'doctor'|'system'};
export type ClinicalState={schemaVersion:2;status:EncounterStatus;appointmentConfirmed:boolean;intakeComplete:boolean;planConfirmed:boolean;teachbackComplete:boolean;taken:number;missed:number;urgent:boolean;urgentResolved:boolean;urgentResponse?:string;plan:TreatmentPlan|null;logs:AuditEvent[]};
export const seedState:ClinicalState={schemaVersion:2,status:'previsit-draft',appointmentConfirmed:false,intakeComplete:false,planConfirmed:false,teachbackComplete:false,taken:41,missed:1,urgent:false,urgentResolved:false,plan:null,logs:[]};
const statuses=new Set<EncounterStatus>(['previsit-draft','previsit-submitted','nurse-intake','ready-for-doctor','doctor-examining','doctor-plan-confirmed','nurse-education','home-care-active','return-visit-due','return-visit-checked-in','admission-requested','inpatient','discharge-planning','discharged-home']);
export function migrate(raw:unknown):ClinicalState{const x=(raw&&typeof raw==='object'?raw:{}) as any;const legacyPlan=x.planConfirmed?{planId:'plan-demo-001',revision:1,status:x.teachbackComplete?'Active at home':'Doctor confirmed',createdBy:'doctor' as const,confirmedAt:new Date(0).toISOString(),changeSummary:'Migrated from legacy prototype state',medication:{name:'Osimertinib',dose:'80 mg',route:'PO',schedule:'once daily'}}:null;return {schemaVersion:2,status:statuses.has(x.status)?x.status:seedState.status,appointmentConfirmed:!!x.appointmentConfirmed,intakeComplete:!!x.intakeComplete,planConfirmed:!!x.planConfirmed,teachbackComplete:!!x.teachbackComplete,taken:Number.isFinite(x.taken)?Math.max(0,x.taken):41,missed:Number.isFinite(x.missed)?Math.max(0,x.missed):1,urgent:!!x.urgent,urgentResolved:!!x.urgentResolved,urgentResponse:typeof x.urgentResponse==='string'?x.urgentResponse:undefined,plan:normalizePlan(x.plan)||legacyPlan,logs:Array.isArray(x.logs)?x.logs.filter((e:any)=>e&&typeof e.event==='string').map((e:any)=>({at:typeof e.at==='string'?e.at:new Date(0).toISOString(),event:e.event,actor:['patient','nurse','doctor','system'].includes(e.actor)?e.actor:'system'})):[]};}
function normalizePlan(p:any):TreatmentPlan|null{if(!p||typeof p!=='object')return null;return {planId:typeof p.planId==='string'?p.planId:'plan-demo-001',revision:Number.isFinite(p.revision)?Math.max(1,p.revision):1,status:['Draft','Doctor confirmed','Nurse educated','Active at home','Superseded','Held','Completed'].includes(p.status)?p.status:'Draft',createdBy:'doctor',confirmedAt:typeof p.confirmedAt==='string'?p.confirmedAt:null,changeSummary:typeof p.changeSummary==='string'?p.changeSummary:'',medication:{name:typeof p.medication?.name==='string'?p.medication.name:'Osimertinib',dose:typeof p.medication?.dose==='string'?p.medication.dose:'80 mg',route:typeof p.medication?.route==='string'?p.medication.route:'PO',schedule:typeof p.medication?.schedule==='string'?p.medication.schedule:'once daily'}}}
export function parseStored(text:string|null):ClinicalState{if(!text)return seedState;try{return migrate(JSON.parse(text))}catch{return seedState}}
export function transition(state:ClinicalState,event:string,actor:AuditEvent['actor'],patch:Partial<ClinicalState>={}):ClinicalState{let next={...state,...patch};if(event==='DOCTOR_PLAN_CONFIRMED'){next={...next,planConfirmed:true,status:'doctor-plan-confirmed',plan:{planId:state.plan?.planId||'plan-demo-001',revision:(state.plan?.revision||0)+1,status:'Doctor confirmed',createdBy:'doctor',confirmedAt:new Date().toISOString(),changeSummary:'Continue osimertinib 80 mg daily; monitor grade 2 diarrhea and mild rash',medication:{name:'Osimertinib',dose:'80 mg',route:'PO',schedule:'once daily'}}};}if(event==='NURSE_EDUCATION_COMPLETED'&&next.plan){next={...next,teachbackComplete:true,status:'home-care-active',plan:{...next.plan,status:'Active at home'}};}return {...next,logs:[...state.logs,{at:new Date().toISOString(),event,actor}]};}