import { WORKFLOW_LABELS, getRoleTasks } from '../workflow.js';
import { caseMatches, casePriority, isCaseArchived, queueCounts, waitingFor } from '../cases.js';
import { decisionHistoryPanel } from '../decisionHistory.js';
import { buildMdtPacket, mdtPacketPanel } from '../mdt.js';

export const ROLE_META = { doctor: { label: 'Bác sĩ', eyebrow: 'Doctor workspace' }, nurse: { label: 'Điều dưỡng', eyebrow: 'Nurse workspace' }, patient: { label: 'Bệnh nhân', eyebrow: 'Patient workspace' } };
export function escapeHtml(value = '') { return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;'); }
export function taskList(state, role) { const items = getRoleTasks(state, role); return `<section class="panel"><div class="panel-head"><div><div class="eyebrow">Nhiệm vụ</div><h2>Việc cần làm</h2></div><span class="state-chip">${escapeHtml(WORKFLOW_LABELS[state.workflow.state] || state.workflow.state)}</span></div><div class="task-list">${items.map(task => `<div class="task ${task.status}"><div class="task-mark">${task.status === 'done' ? '✓' : task.status === 'active' ? '•' : '–'}</div><div><strong>${escapeHtml(task.title)}</strong><p>${escapeHtml(task.detail)}</p></div></div>`).join('')}</div></section>`; }
export function patientHeader(state) { const p = state.patient; const archived = isCaseArchived(state); return `<section class="patient-strip"><div><div class="eyebrow">Ca bệnh hiện tại ${archived ? '· ĐÃ ĐÓNG' : ''}</div><h2>${escapeHtml(p.name)} <span class="demo-tag">DEMO</span></h2><p>${escapeHtml(p.id)} · ${p.age} tuổi · ECOG ${p.ecog} · ${escapeHtml(p.diagnosis)}</p><p class="assignment-line">BS: ${escapeHtml(state.assignment?.doctor || 'Chưa phân công')} · ĐD: ${escapeHtml(state.assignment?.nurse || 'Chưa phân công')}</p></div><div class="tnm-box"><span>TNM demo</span><strong>${escapeHtml(p.tnm)}</strong><small>${escapeHtml(p.stage)}</small></div></section>`; }
export function timeline(state) { const events = [...state.events].reverse().slice(0, 6); return `<section class="panel"><div class="eyebrow">Activity</div><h2>Dòng sự kiện</h2><div class="timeline">${events.map(event => `<div class="timeline-item"><span></span><div><strong>${escapeHtml(event.text)}</strong><small>${new Date(event.at).toLocaleString('vi-VN')}</small></div></div>`).join('')}</div></section>`; }

export function teamQueue(state, role) {
  const counts = queueCounts(state); const rank = { urgent: 0, attention: 1, routine: 2 }; const filter = state.ui?.queueFilter || 'all'; const search = state.ui?.caseSearch || '';
  const cases = [...state.cases].sort((a,b) => rank[casePriority(a)] - rank[casePriority(b)]).filter(item => caseMatches(item, search)).filter(item => filter === 'archived' ? isCaseArchived(item) : !isCaseArchived(item) && (filter === 'all' || casePriority(item) === filter));
  return `<section class="panel team-queue"><div class="panel-head"><div><div class="eyebrow">Team dashboard</div><h2>Case management</h2></div><button class="primary-btn compact" data-action="open-new-case">+ Ca mới</button></div>
  <div class="queue-metrics"><div><strong>${counts.urgent}</strong><span>ưu tiên cao</span></div><div><strong>${role === 'doctor' ? counts.doctor : counts.nurse}</strong><span>chờ ${role === 'doctor' ? 'bác sĩ' : 'điều dưỡng'}</span></div><div><strong>${counts.archived}</strong><span>đã đóng</span></div></div>
  <input class="queue-search" id="caseSearch" value="${escapeHtml(search)}" placeholder="Tìm tên, mã ca, chẩn đoán…" />
  <div class="queue-filters"><button data-action="queue-filter" data-filter="all" class="${filter==='all'?'active':''}">Đang mở</button><button data-action="queue-filter" data-filter="urgent" class="${filter==='urgent'?'active':''}">Ưu tiên</button><button data-action="queue-filter" data-filter="attention" class="${filter==='attention'?'active':''}">Đang chờ</button><button data-action="queue-filter" data-filter="archived" class="${filter==='archived'?'active':''}">Đã đóng</button></div>
  <div class="queue-list">${cases.length ? cases.map(item => { const priority=casePriority(item); return `<button class="queue-case ${item.id===state.activeCaseId?'active':''} ${priority}" data-action="select-case" data-case-id="${escapeHtml(item.id)}"><span class="priority-dot"></span><span class="queue-copy"><strong>${escapeHtml(item.patient.name)} ${item.unreadAlerts ? `<i class="alert-count">${item.unreadAlerts}</i>`:''}</strong><small>${escapeHtml(item.patient.id)} · ${escapeHtml(item.patient.diagnosis)}</small><em>${isCaseArchived(item) ? 'Đã đóng' : `Chờ: ${escapeHtml(waitingFor(item))}`}</em></span><b>${priority==='urgent'?'!':'›'}</b></button>`; }).join('') : '<div class="queue-empty">Không có ca phù hợp.</div>'}</div></section>`;
}

export function caseAdminPanel(state) { return `<section class="panel case-admin"><div class="panel-head"><div><div class="eyebrow">Quản lý ca</div><h2>Phân công & trạng thái</h2></div></div><div class="field-grid"><label><span>Bác sĩ phụ trách</span><input id="assignedDoctor" value="${escapeHtml(state.assignment?.doctor || '')}" placeholder="VD: BS. Nguyễn An" /></label><label><span>Điều dưỡng phụ trách</span><input id="assignedNurse" value="${escapeHtml(state.assignment?.nurse || '')}" placeholder="VD: ĐD. Trần Mai" /></label></div><div class="action-row"><button class="secondary-btn" data-action="save-assignment">Lưu phân công</button>${isCaseArchived(state) ? '<button class="secondary-btn" data-action="reopen-case">Mở lại ca</button>' : '<button class="danger-btn" data-action="archive-case">Đóng ca</button>'}</div><p class="helper-text">Demo cục bộ: phân công và đóng ca chưa đồng bộ giữa thiết bị.</p></section>`; }

export function newCaseModal(state) { if (!state.ui?.newCaseOpen) return ''; return `<div class="modal-backdrop"><section class="modal-card"><div class="panel-head"><div><div class="eyebrow">Synthetic demo</div><h2>Tạo ca mới</h2></div><button class="ghost-btn" data-action="close-new-case">Đóng</button></div><div class="field-grid"><label><span>Họ tên</span><input id="newCaseName" placeholder="Tên bệnh nhân demo" /></label><label><span>Tuổi</span><input id="newCaseAge" type="number" min="0" max="120" /></label><label><span>Giới</span><select id="newCaseSex"><option>Nam</option><option>Nữ</option><option>Khác</option></select></label><label><span>Chẩn đoán ban đầu</span><input id="newCaseDiagnosis" value="Nghi ung thư phổi" /></label></div><div class="action-row"><button class="primary-btn" data-action="create-case">Tạo ca demo</button></div></section></div>`; }

export function workspaceShell(state, role, body) { const meta=ROLE_META[role]; const staff=role==='nurse'?`<div class="staff-queue-wide">${teamQueue(state,role)}</div>`:''; const admin=['doctor','nurse'].includes(role)?caseAdminPanel(state):''; const mdt=role==='doctor'?`${mdtPacketPanel(state)}<div hidden data-mdt-packet-text="${escapeHtml(buildMdtPacket(state))}"></div>`:''; const audit=role==='doctor'?decisionHistoryPanel(state):''; return `<div class="workspace-shell"><header class="appbar"><a class="brand" href="#/">LungCare <span>Oncology</span></a><div class="appbar-actions"><span class="role-badge">${meta.label}</span><button class="ghost-btn" data-action="switch-role">Đổi vai trò</button></div></header><main class="workspace"><div class="workspace-title"><div><div class="eyebrow">${meta.eyebrow}</div><h1>${meta.label}</h1></div><div class="save-status" id="saveStatus">Đã lưu cục bộ</div></div>${staff}${patientHeader(state)}${admin}${body}${mdt}${audit}</main>${newCaseModal(state)}</div>`; }
