const STORAGE_KEY='lungcare.phase1.state';
const GENES=['EGFR','ALK','ROS1','BRAF V600E','KRAS G12C','MET exon 14','RET','NTRK','HER2 / ERBB2'];
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{return null}};
const write=s=>localStorage.setItem(STORAGE_KEY,JSON.stringify(s));
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function active(state){return state?.cases?.find(x=>x.id===state.activeCaseId)||null}
function normalized(c){
 const d=c?.doctorReview||{},stored=d.biomarkerResults||{},tests={};
 for(const gene of GENES){const prev=stored.tests?.[gene];tests[gene]=prev?{status:prev.status||'pending',alteration:prev.alteration||''}:{status:d.biomarkers?.[gene]?'resulted_unknown':'pending',alteration:''}}
 const p=stored.pdl1||{};return {tests,pdl1:{status:p.status||(d.biomarkers?.['PD-L1']?'resulted_unknown':'pending'),tps:p.tps??''},updatedAt:stored.updatedAt||null};
}
function options(current){return [['pending','Pending'],['positive','Positive'],['negative','Negative'],['not_tested','Not tested'],['resulted_unknown','Legacy — result unknown']].map(([v,l])=>`<option value="${v}" ${current===v?'selected':''}>${l}</option>`).join('')}
function panel(c){const b=normalized(c);return `<section class="panel biomarker-structured" data-structured-biomarker-editor><div class="panel-head"><div><div class="eyebrow">Phase 17 · Structured biomarkers</div><h2>Molecular results & PD-L1</h2></div><span class="evidence-chip">Clinician-entered</span></div><div class="clinical-note">Không suy diễn kết quả từ checkbox legacy. Mỗi marker phải có trạng thái riêng; alteration chỉ nhập khi positive. PD-L1 TPS là dữ liệu riêng và không tự chọn treatment.</div><div class="structured-biomarker-grid">${GENES.map((g,i)=>{const x=b.tests[g];return `<div class="structured-biomarker-row"><strong>${esc(g)}</strong><select data-bio-status="${i}">${options(x.status)}</select><input data-bio-alt="${i}" value="${esc(x.alteration)}" placeholder="Alteration / fusion / variant nếu positive"></div>`}).join('')}<div class="structured-biomarker-row pdl1"><strong>PD-L1</strong><select id="structuredPdl1Status">${[['pending','Pending'],['resulted','Resulted'],['not_tested','Not tested'],['resulted_unknown','Legacy — result unknown']].map(([v,l])=>`<option value="${v}" ${b.pdl1.status===v?'selected':''}>${l}</option>`).join('')}</select><input id="structuredPdl1Tps" type="number" min="0" max="100" step="1" value="${esc(b.pdl1.tps)}" placeholder="TPS %"></div></div><div class="helper-text">ASCO Stage IV Living Guideline v2026.3.3 nhấn mạnh biomarker availability tại thời điểm quyết định; module này chỉ cấu trúc dữ liệu, không kê đơn.</div><div class="action-row"><button class="primary-btn" data-action="save-structured-biomarkers">Lưu structured biomarkers</button></div>${b.updatedAt?`<small>Cập nhật: ${new Date(b.updatedAt).toLocaleString('vi-VN')}</small>`:''}</section>`}
function inject(){const state=read(),c=active(state),root=document.querySelector('.workspace');if(!root||!c||state.activeRole!=='doctor'||document.querySelector('[data-structured-biomarker-editor]'))return;const marker=root.querySelector('.patient-strip');if(marker)marker.insertAdjacentHTML('afterend',panel(c));else root.insertAdjacentHTML('beforeend',panel(c))}
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);
document.addEventListener('click',e=>{const btn=e.target.closest('[data-action="save-structured-biomarkers"]');if(!btn)return;const state=read(),idx=state?.cases?.findIndex(x=>x.id===state.activeCaseId);if(idx==null||idx<0)return alert('Không tìm thấy ca hiện tại.');const c=state.cases[idx],d=c.doctorReview||{},tests={};let anyPositive=false,allMolecularFinal=true;GENES.forEach((g,i)=>{const status=document.querySelector(`[data-bio-status="${i}"]`)?.value||'pending',alteration=document.querySelector(`[data-bio-alt="${i}"]`)?.value.trim()||'';tests[g]={status,alteration};if(status==='positive')anyPositive=true;if(!['positive','negative'].includes(status))allMolecularFinal=false});const pStatus=document.getElementById('structuredPdl1Status')?.value||'pending',rawTps=document.getElementById('structuredPdl1Tps')?.value??'',tps=rawTps===''?'':Number(rawTps);if(pStatus==='resulted'&&(tps===''||tps<0||tps>100))return alert('PD-L1 TPS phải từ 0 đến 100 khi trạng thái là Resulted.');for(const g of GENES){if(tests[g].status==='positive'&&!tests[g].alteration)return alert(`${g}: cần ghi alteration/variant khi chọn Positive.`)}const structured={tests,pdl1:{status:pStatus,tps},updatedAt:new Date().toISOString()},legacy={...(d.biomarkers||{})};for(const g of GENES)legacy[g]=['positive','negative'].includes(tests[g].status);legacy['PD-L1']=pStatus==='resulted';legacy.__structuredFingerprint=JSON.stringify(structured);const positives=GENES.filter(g=>tests[g].status==='positive'),driverName=positives.map(g=>tests[g].alteration||g).join('; '),complete=allMolecularFinal&&pStatus==='resulted';const tc=d.treatmentContext||{};state.cases[idx]={...c,doctorReview:{...d,biomarkerResults:structured,biomarkerStatus:complete?'complete':'pending',biomarkers:legacy,treatmentContext:{...tc,driverStatus:anyPositive?'present':(complete?'none':'pending'),driverName:anyPositive?driverName:'',decisionReviewed:false}},events:[...(c.events||[]),{id:crypto.randomUUID(),type:'STRUCTURED_BIOMARKERS_SAVED',role:'doctor',text:`Đã lưu structured biomarker results${complete?' · workup complete':' · còn pending/not tested'}.`,at:structured.updatedAt}]};write(state);location.reload()});
