const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const esc=(v='')=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const active=s=>s?.cases?.find(x=>x.id===s.activeCaseId)||null;
function passportId(c){return `LC-${String(c?.patient?.id||c?.id||'DEMO').replace(/[^A-Z0-9]/gi,'').toUpperCase()}`}
function biomarkerSummary(c){const b=c.doctorReview?.biomarkerResults||{},tests=b.tests||{};const pos=Object.entries(tests).filter(([,x])=>x?.status==='positive').map(([g,x])=>`${g}${x.alteration?` ${x.alteration}`:''}`);const p=b.pdl1?.status==='resulted'&&b.pdl1?.tps!==''?`PD-L1 ${b.pdl1.tps}%`:'';return [...pos,p].filter(Boolean).join(' · ')||'Chưa có biomarker cấu trúc hoàn chỉnh'}
function txSummary(c){const tx=c.clinicalMonitoring?.currentTreatment||{};return [tx.name,tx.cycle,tx.status].filter(Boolean).join(' · ')||'Chưa ghi điều trị hiện tại'}
function latestImaging(c){return [...(c.clinicalMonitoring?.imaging||[])].reverse()[0]||null}
function urgentHistory(c){return [...(c.events||[])].filter(e=>['PATIENT_URGENT_SYMPTOM','URGENT_SUPPORT_REQUEST','TRIAGE_COMPLETED'].includes(e.type)).slice(-4).reverse()}
function snapshot(c){const img=latestImaging(c),d=c.doctorReview||{},decision=d.treatmentContext?.decision||{},events=urgentHistory(c);return `LUNGCARE CARE PASSPORT — DEMO\nPassport ID: ${passportId(c)}\nPatient: ${c.patient?.name||'—'} (${c.patient?.id||'—'})\nDiagnosis: ${c.patient?.diagnosis||'—'}\nStage: ${d.stagingInput?.calculatedStage||c.patient?.stage||'—'}\nCurrent treatment: ${txSummary(c)}\nLatest imaging: ${img?`${img.date||'—'} · ${img.modality||'CT'} · ${img.response||'—'} · ${img.note||''}`:'Chưa có'}\nBiomarkers: ${biomarkerSummary(c)}\nLatest clinician decision: ${decision.optionTitle||decision.selectedOptionId||'Chưa có'}\nRecent urgent/triage events:\n${events.length?events.map(e=>`- ${new Date(e.at).toLocaleString('vi-VN')}: ${e.text}`).join('\n'):'- Chưa có'}\n\nPatient-tracking & clinical decision-support summary. Not an EHR. Verify patient-reported and transferred data before clinical use.`}
function panel(c,role){const img=latestImaging(c),d=c.doctorReview||{},decision=d.treatmentContext?.decision||{};return `<section class="care-passport" data-care-passport><div class="passport-head"><div><div class="eyebrow">Care Passport</div><h2>Sổ điều trị số đi cùng bệnh nhân</h2><p>Một clinical snapshot để chuẩn bị tái khám/chuyển bác sĩ. Không phải bệnh án điện tử.</p></div><div class="passport-id"><span>Passport ID</span><strong>${esc(passportId(c))}</strong><small>QR-ready · demo-local</small></div></div><div class="passport-grid"><div><span>Điều trị hiện tại</span><strong>${esc(txSummary(c))}</strong></div><div><span>CT gần nhất</span><strong>${img?esc(`${img.response||'Chưa đánh giá'} · ${img.date||'chưa ngày'}`):'Chưa có'}</strong></div><div><span>Genomic / PD-L1</span><strong>${esc(biomarkerSummary(c))}</strong></div><div><span>Quyết định gần nhất</span><strong>${esc(decision.optionTitle||decision.selectedOptionId||'Chưa có')}</strong></div></div><div class="passport-actions"><button class="secondary-btn" data-action="passport-open">Mở Care Passport</button><button class="ghost-btn" data-action="passport-copy-id">Copy Passport ID</button></div>${role==='patient'?'<p class="helper-text">Bản demo chưa đồng bộ cross-device. Khi có backend/auth, Passport ID này có thể trở thành QR/link chia sẻ có kiểm soát.</p>':''}</section>`}
function modal(c){const events=urgentHistory(c),img=latestImaging(c);return `<div class="passport-modal" data-passport-modal><section class="passport-dialog"><div class="panel-head"><div><div class="eyebrow">Longitudinal care summary</div><h2>${esc(c.patient?.name||'Care Passport')}</h2></div><button class="ghost-btn" data-action="passport-close">Đóng</button></div><div class="passport-banner"><span>${esc(passportId(c))}</span><b>${esc(c.patient?.diagnosis||'')}</b></div><div class="passport-detail-grid"><article><span>Stage</span><strong>${esc(c.doctorReview?.stagingInput?.calculatedStage||c.patient?.stage||'—')}</strong></article><article><span>Current treatment</span><strong>${esc(txSummary(c))}</strong></article><article><span>Biomarkers</span><strong>${esc(biomarkerSummary(c))}</strong></article><article><span>Latest CT response</span><strong>${img?esc(`${img.response||'—'} · ${img.date||'—'}`):'Chưa có'}</strong></article></div><div class="passport-section"><div class="eyebrow">Recent urgent / triage events</div>${events.length?events.map(e=>`<div class="passport-event"><span>${new Date(e.at).toLocaleString('vi-VN')}</span><strong>${esc(e.text)}</strong></div>`).join(''):'<div class="empty-state">Chưa có sự kiện khẩn/triage gần đây.</div>'}</div><div class="passport-section"><div class="eyebrow">Clinical snapshot</div><pre>${esc(snapshot(c))}</pre></div><div class="action-row"><button class="primary-btn" data-action="passport-copy-summary">Copy clinical snapshot</button></div><p class="helper-text">Dữ liệu chuyển tiếp cần được clinician xác minh. Demo hiện lưu cục bộ trong browser; chưa phải cơ chế trao đổi hồ sơ y tế.</p></section></div>`}
function inject(){const s=read(),c=active(s),root=document.querySelector('.workspace');if(!s||!c||!root||document.querySelector('[data-care-passport]'))return;const marker=root.querySelector('.patient-strip');if(marker)marker.insertAdjacentHTML('afterend',panel(c,s.activeRole))}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(!a?.startsWith('passport-'))return;const s=read(),c=active(s);if(!c)return;if(a==='passport-open'){document.body.insertAdjacentHTML('beforeend',modal(c));return}if(a==='passport-close'){document.querySelector('[data-passport-modal]')?.remove();return}if(a==='passport-copy-id'||a==='passport-copy-summary'){const text=a==='passport-copy-id'?passportId(c):snapshot(c);try{await navigator.clipboard.writeText(text);b.textContent='Đã copy';setTimeout(()=>b.textContent=a==='passport-copy-id'?'Copy Passport ID':'Copy clinical snapshot',1200)}catch{alert(text)}return}},true);
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);
