const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const esc=(v='')=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const active=s=>s?.cases?.find(x=>x.id===s.activeCaseId)||null;
function push(arr,at,type,title,detail,priority='routine'){if(!at)return;arr.push({at,type,title,detail,priority})}
function build(c){const out=[],m=c.clinicalMonitoring||{},t=c.patientTracking||{},dr=c.doctorReview||{};
(m.imaging||[]).forEach(x=>push(out,x.createdAt||x.at||x.date,'imaging',`${x.modality||'Imaging'} · ${x.response||'Chưa đánh giá'}`,x.note||'',x.response==='Tiến triển bệnh'?'high':'routine'));
(t.checkins||[]).forEach(x=>push(out,x.at,'symptom','Patient symptom check-in',x.summary||'',x.report&&(x.report.hemoptysis||x.report.confusion||x.report.chestPain||x.report.dyspnea==='Tăng nhiều')?'high':'routine'));
if(t.toxicity?.updatedAt)push(out,t.toxicity.updatedAt,'toxicity','Thuốc & độc tính cập nhật',`Adherence: ${t.toxicity.adherence||'—'} · Mệt ${t.toxicity.fatigue||'—'} · Nôn ${t.toxicity.nausea||'—'} · Tiêu chảy ${t.toxicity.diarrhea||'—'}`,['severe'].some(v=>Object.values(t.toxicity).includes(v))||t.toxicity.adherence==='stopped'?'high':'routine');
(m.urgentTriage||[]).forEach(x=>push(out,x.resolvedAt||x.createdAt,'triage',`Urgent triage · ${x.priority||'—'}`,`${x.disposition||''}${x.note?` · ${x.note}`:''}`,'high'));
(dr.decisionHistory||[]).forEach(x=>push(out,x.decidedAt||x.at,'decision','Clinician treatment decision',x.selectedOptionTitle||x.selectedOptionId||'Decision saved','routine'));
if(m.currentTreatment?.updatedAt)push(out,m.currentTreatment.updatedAt,'treatment','Điều trị hiện tại cập nhật',`${m.currentTreatment.name||'—'} · ${m.currentTreatment.cycle||''} · ${m.currentTreatment.status||''}`,'routine');
return out.filter(x=>x.at).sort((a,b)=>new Date(b.at)-new Date(a.at))}
function latestAnchor(events){return events.find(x=>['imaging','decision','treatment'].includes(x.type))?.at||events.at(-1)?.at||null}
function whatChanged(events){const anchor=latestAnchor(events);const recent=anchor?events.filter(x=>new Date(x.at)>=new Date(anchor)).slice(0,6):events.slice(0,6);const high=recent.filter(x=>x.priority==='high');return{anchor,recent,headline:high.length?`${high.length} thay đổi ưu tiên cao cần xem trước`:(recent.length?`${recent.length} cập nhật mới kể từ mốc gần nhất`:'Chưa có thay đổi mới')}}
function panel(c){const events=build(c),chg=whatChanged(events);return `<section class="clinical-timeline" data-clinical-timeline><div class="timeline-head"><div><div class="eyebrow">AI clinical timeline · demo synthesis</div><h2>What changed since last visit?</h2><p>${esc(chg.headline)}. Tóm tắt được dựng từ dữ liệu đang có, không tự tạo chẩn đoán hay y lệnh.</p></div><span class="timeline-count">${events.length} events</span></div><div class="change-strip">${chg.recent.length?chg.recent.map(x=>`<div class="change-chip ${x.priority==='high'?'high':''}"><span>${new Date(x.at).toLocaleDateString('vi-VN')}</span><strong>${esc(x.title)}</strong></div>`).join(''):'<div class="empty-state">Chưa có event đủ dữ liệu.</div>'}</div><div class="timeline-list">${events.slice(0,12).map(x=>`<article class="timeline-item ${x.priority==='high'?'high':''}"><div class="timeline-dot"></div><div><small>${new Date(x.at).toLocaleString('vi-VN')} · ${esc(x.type)}</small><strong>${esc(x.title)}</strong><p>${esc(x.detail||'')}</p></div></article>`).join('')||'<div class="empty-state">Chưa có timeline.</div>'}</div></section>`}
function inject(){const s=read(),c=active(s),root=document.querySelector('.workspace');if(!root||!c||s.activeRole!=='doctor'||document.querySelector('[data-clinical-timeline]'))return;const cockpit=root.querySelector('[data-doctor-cockpit]');if(cockpit)cockpit.insertAdjacentHTML('afterend',panel(c))}
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);
