export const SCHEMA_VERSION = 4;

export function createDemoState() {
  return {
    schemaVersion: SCHEMA_VERSION,
    activeRole: null,
    ui: {
      doctorStep: 'overview',
      nurseStep: 'overview',
    },
    workflow: {
      state: 'NURSE_INTAKE',
      updatedAt: new Date().toISOString(),
    },
    patient: {
      id: 'DEMO-LC-001',
      synthetic: true,
      name: 'Nguyễn Văn Minh',
      age: 62,
      sex: 'Nam',
      smokingPackYears: 35,
      ecog: 1,
      diagnosis: 'Nghi NSCLC',
      tnm: 'cT2b N2 M0',
      stage: 'Giai đoạn IIIB (demo)',
      redFlags: [],
    },
    intake: {
      spo2: 96,
      heartRate: 82,
      temperature: 36.8,
      systolicBP: 128,
      diastolicBP: 76,
      dyspnea: 'Nhẹ khi gắng sức',
      pain: 2,
      note: 'Ho kéo dài, đau ngực nhẹ, sụt 4 kg/2 tháng.',
      redFlags: {
        severeDyspnea: false,
        majorHemoptysis: false,
        alteredMentalStatus: false,
        chestPainAcute: false,
      },
      escalationAcknowledged: false,
      medicationSafety: {
        allergiesReviewed: false,
        allergies: 'Chưa ghi nhận dị ứng thuốc trong dữ liệu demo.',
        medicationsReviewed: false,
        currentMedications: 'Amlodipine 5 mg mỗi ngày (demo).',
        interactionConcern: '',
      },
      education: {
        identityConfirmed: false,
        teachBackCompleted: false,
        supportPerson: '',
        educationNote: '',
      },
      handoff: {
        situation: 'Nghi ung thư phổi, đang chờ hoàn tất đánh giá bác sĩ.',
        background: 'Nam 62 tuổi, 35 pack-year, ECOG 1.',
        assessment: '',
        recommendation: 'Bác sĩ đánh giá staging, mô bệnh học và kế hoạch tiếp theo.',
      },
      completed: false,
    },
    doctorReview: {
      diagnosisConfirmed: false,
      pathologyType: 'NSCLC — chưa định subtype',
      pathologyReviewed: false,
      pathologyNote: 'Chưa có kết quả mô bệnh học xác nhận trong dữ liệu demo.',
      stagingReviewed: false,
      diseaseExtent: 'locoregional',
      n2Status: 'suspected',
      nodalConfirmationPlan: '',
      biomarkerStatus: 'pending',
      biomarkers: {
        'EGFR': false,
        'ALK': false,
        'ROS1': false,
        'BRAF V600E': false,
        'KRAS G12C': false,
        'MET exon 14': false,
        'RET': false,
        'NTRK': false,
        'HER2 / ERBB2': false,
        'PD-L1': false,
      },
      mdtDecision: '',
      plan: 'Chờ hoàn tất đánh giá mô bệnh học/hạch trung thất và hội chẩn MDT.',
      completed: false,
    },
    patientEducation: {
      acknowledged: false,
    },
    events: [
      {
        id: crypto.randomUUID(),
        type: 'CASE_CREATED',
        role: 'system',
        text: 'Khởi tạo ca bệnh demo.',
        at: new Date().toISOString(),
      },
    ],
  };
}
