import { decisionFingerprint } from './treatment.js';

function esc(value=''){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function parseFingerprint(value){try{return JSON.parse(value||'{}')}catch{return{}}}
const LABELS={stage:'TNM stage',pathologyType:'Mô bệnh học',biomarkerStatus:'Biomarker status',biomarkers:'Biomarker checklist',intent:'Treatment intent',resectability:'Resectability',fitness:'Fitness',driverStatus:'Driver status',driverName:'Driver alteration',contraindicationsReviewed:'Safety review',contraindicationsNote:'Safety context'};
function same(a,b){return JSON.stringify(a)===JSON.stringify(b)}
export function changedContext(snapshotFingerprint,currentFingerprint){const before=parseFingerprint(snapshotFingerprint),now=parseFingerprint(currentFingerprint);return Object.keys({...before,...now}).filter(k=>!same(before[k],now[k])).map(k=>({key:k,label:LABELS[k]||k,before:before[k],now:now[k]}))}
function val(v){if(Array.isArray(v))return v.join(', ')||'—';if(v&&typeof v==='object')return JSON.stringify(v);if(v===true)return'Có';if(v===false)return'Không';return String(v??'—')}
export function decisionHistoryPanel(state){const tc=state.doctorReview?.treatmentContext||{},history=[...(tc.decisionHistory||[])].reverse(),currentFp=decisionFingerprint(state),current=tc.decision||{},currentChanges=current.decidedAt?changedContext(current.contextFingerprint,currentFp):[];return `<section class="panel decision-history-panel"><div class="panel-head"><div><div class="eyebrow">Clinical audit trail</div><h2>Lịch sử quyết định</h2></div><span class="state-chip">${history.length} version</span></div>${current.decidedAt&&currentChanges.length?`<div class="impact-alert"><strong>Clinical context đã thay đổi</strong><span>${currentChanges.map(x=>esc(x.label)).join(' · ')}</span><label><input id="decisionImpactReviewed" type="checkbox"> Tôi đã review ảnh hưởng của các thay đổi trước khi lưu quyết định mới.</label></div>`:''}${history.length?`<div class="decision-history-list">${history.map((item,index)=>{const changes=changedContext(item.contextFingerprint,currentFp);return `<article class="decision-history-item ${index===0?'latest':''}"><header><div><span>Version ${history.length-index}</span><strong>${esc(item.selectedOptionId||'Không rõ option')}</strong></div><time>${item.decidedAt?new Date(item.decidedAt).toLocaleString('vi-VN'):'Không rõ thời điểm'}</time></header><p>${esc(item.rationale||'Không có rationale')}</p><div class="history-meta"><span>${esc(item.pathwayKey||'')}</span><span>${esc(item.sourceUpdated||'')}</span></div>${changes.length?`<details><summary>${changes.length} thay đổi so với context hiện tại</summary><div class="impact-diff">${changes.map(x=>`<div><b>${esc(x.label)}</b><small>Cũ: ${esc(val(x.before))}</small><small>Hiện tại: ${esc(val(x.now))}</small></div>`).join('')}</div></details>`:'<div class="history-current">Context vẫn khớp snapshot này.</div>'}</article>`}).join('')}</div>`:'<div class="queue-empty">Chưa có quyết định điều trị được lưu.</div>'}<p class="helper-text">History là snapshot audit cục bộ của demo; không thay thế hồ sơ y khoa hoặc chữ ký điện tử.</p></section>`}

if(typeof document!=='undefined')document.addEventListener('click',event=>{const button=event.target.closest?.('[data-action="save-treatment-decision"]');if(!button)return;const alertBox=document.querySelector('.impact-alert');if(alertBox&&!document.getElementById('decisionImpactReviewed')?.checked){event.preventDefault();event.stopImmediatePropagation();window.alert('Clinical context đã thay đổi. Cần xác nhận đã review change impact trước khi lưu quyết định mới.');}},true);
