const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=(v='')=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const active=s=>s?.cases?.find(x=>x.id===s.activeCaseId)||null;
function sourceContext(c,e){const tx=c.clinicalMonitoring?.currentTreatment||{},tox=c.patientTracking?.toxicity||{},u=(c.urgentTriage||[]).find(x=>x.id===e.sourceId),last=[...(c.patientTracking?.checkins||[])].reverse()[0],p=c.patientTracking?.previsit||{};const source=e.sourceType==='urgent'?`${u?.reason||'Urgent call'}${u?.note?` — ${u.note}`:''}`:e.sourceType==='toxicity'?`${tox.note||'Độc tính/adherence'} · ${tox.adherence||'chưa adherence'}`:e.sourceType==='previsit'?`${p.concern||p.change||'Pre-visit update'}`:`${last?.summary||'Symptom check-in'}`;return{tx,tox,source}}
function openEscalations(c){return [...(c.nurseEscalations||[])].filter(x=>x.status!=='resolved').sort((a,b)=>new Date(b.escalatedAt||0)-new Date(a.escalatedAt||0))}
function panel(c){const items=openEscalations(c);return `<section class="doctor-escalation" data-doctor-escalation><div class="doctor-escalation-head"><div><div class="eyebrow">Doctor escalation inbox</div><h2>Escalation từ điều dưỡng</h2><p>Dữ liệu đã qua bước nurse verification trước khi bác sĩ review.</p></div><span class="escalation-count">${items.length} open</span></div><div class="escalation-list">${items.length?items.map(x=>`<article class="escalation-item ${x.doctorAckAt?'ack':''}"><div><span>${esc(x.sourceType)}</span><strong>${esc(x.note||'Escalation cần bác sĩ review')}</strong><small>${x.escalatedAt?new Date(x.escalatedAt).toLocaleString('vi-VN'):''}</small></div><div><em>${x.doctorAckAt?'Acknowledged':'New'}</em><button data-action="doctor-open-escalation" data-id="${esc(x.id)}">Mở</button></div></article>`).join(''):'<div class="empty-state">Không có escalation mở.</div>'}</div></section>`}
function modal(c,e){const ctx=sourceContext(c,e),v=e.verification||{},u=(c.urgentTriage||[]).find(x=>x.id===e.sourceId);return `<div class="doctor-escalation-modal" data-doctor-escalation-modal><div class="doctor-escalation-dialog"><div class="panel-head"><div><div class="eyebrow">Shared team handoff</div><h2>${esc(e.sourceType)} escalation</h2></div><button data-action="doctor-close-escalation">Đóng</button></div><div class="doctor-handoff-grid"><div><span>Điều trị hiện tại</span><strong>${esc(ctx.tx.name||'Chưa ghi')}</strong><small>${esc([ctx.tx.cycle,ctx.tx.status].filter(Boolean).join(' · '))}</small></div><div><span>Adherence / toxicity</span><strong>${esc(ctx.tox.adherence||'Chưa cập nhật')}</strong><small>${esc(ctx.tox.note||'')}</small></div><div><span>Signal được escalated</span><strong>${esc(ctx.source)}</strong></div><div><span>Nurse note</span><strong>${esc(e.note||'Không có note')}</strong></div></div><div class="verification-strip"><span class="${v.identity?'done':''}">Danh tính ${v.identity?'✓':'—'}</span><span class="${v.symptoms?'done':''}">Symptoms ${v.symptoms?'✓':'—'}</span><span class="${v.meds?'done':''}">Thuốc ${v.meds?'✓':'—'}</span><span class="${v.redFlags?'done':''}">Red flags ${v.redFlags?'✓':'—'}</span></div>${u?.triage?`<div class="handoff-triage"><b>Urgent triage trước đó</b><span>${esc(u.triage.level||'')} · ${esc(u.triage.disposition||'')}</span><small>${esc(u.triage.note||'')}</small></div>`:''}<label>Ghi chú bác sĩ<textarea id="doctorEscalationNote">${esc(e.doctorNote||'')}</textarea></label><div class="urgent-actions"><button class="secondary-btn" data-action="doctor-ack-escalation" data-id="${esc(e.id)}">Đã nhận</button><button class="primary-btn" data-action="doctor-resolve-escalation" data-id="${esc(e.id)}">Đã review & đóng handoff</button></div><p class="helper-text">Handoff hỗ trợ phối hợp. Quyết định điều trị vẫn được thực hiện trong clinician decision workflow hiện có.</p></div></div>`}
function save(s,c){const i=s.cases.findIndex(x=>x.id===c.id);if(i>=0){s.cases[i]=c;write(s)}}
function inject(){const s=read(),c=active(s),root=document.querySelector('.workspace');if(!s||!c||s.activeRole!=='doctor'||!root||document.querySelector('[data-doctor-escalation]'))return;const marker=root.querySelector('[data-doctor-cockpit]')||root.querySelector('.patient-strip');marker?.insertAdjacentHTML('afterend',panel(c))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const s=read(),c=active(s),a=b.dataset.action;if(!s||!c)return;if(a==='doctor-open-escalation'){e.preventDefault();const item=(c.nurseEscalations||[]).find(x=>x.id===b.dataset.id);if(item)document.body.insertAdjacentHTML('beforeend',modal(c,item))}if(a==='doctor-close-escalation'){e.preventDefault();document.querySelector('[data-doctor-escalation-modal]')?.remove()}if(a==='doctor-ack-escalation'){e.preventDefault();const item=(c.nurseEscalations||[]).find(x=>x.id===b.dataset.id);if(!item)return;item.doctorAckAt=item.doctorAckAt||new Date().toISOString();item.doctorNote=document.getElementById('doctorEscalationNote')?.value?.trim()||item.doctorNote||'';item.updatedAt=new Date().toISOString();c.events=[...(c.events||[]),{id:crypto.randomUUID(),type:'DOCTOR_ESCALATION_ACKNOWLEDGED',role:'doctor',text:`Doctor acknowledged nurse escalation ${item.sourceType}.`,at:item.updatedAt}];save(s,c);location.reload()}if(a==='doctor-resolve-escalation'){e.preventDefault();const item=(c.nurseEscalations||[]).find(x=>x.id===b.dataset.id);if(!item)return;const now=new Date().toISOString();item.status='resolved';item.doctorAckAt=item.doctorAckAt||now;item.doctorResolvedAt=now;item.doctorNote=document.getElementById('doctorEscalationNote')?.value?.trim()||item.doctorNote||'';item.updatedAt=now;c.events=[...(c.events||[]),{id:crypto.randomUUID(),type:'DOCTOR_ESCALATION_RESOLVED',role:'doctor',text:`Doctor reviewed and closed nurse escalation ${item.sourceType}.`,at:now}];save(s,c);location.reload()}},true);
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);
