import { clinicalSnapshot } from './clinical.js';
import { treatmentDecisionStatus, treatmentReadiness } from './treatment.js';

function esc(value=''){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function present(value){return value===undefined||value===null||value===''?'Chưa có':String(value)}
function selectedBiomarkers(d={}){return Object.entries(d.biomarkers||{}).filter(([,done])=>done).map(([name])=>name)}
export function buildMdtPacket(state){const d=state.doctorReview||{},i=state.intake||{},p=state.patient||{},tc=d.treatmentContext||{},dec=tc.decision||{},tr=treatmentReadiness(state),ds=treatmentDecisionStatus(state),snap=clinicalSnapshot(state),checked=selectedBiomarkers(d);const lines=[`MDT REVIEW PACKET — DEMO`,`${present(p.name)} · ${present(p.id)} · ${present(p.age)} tuổi · ECOG ${present(p.ecog)}`,`Diagnosis: ${present(p.diagnosis)}`,`Pathology: ${d.pathologyReviewed?present(d.pathologyType):'Chưa review mô bệnh học'}`,`TNM 9: ${present(p.tnm)} · ${present(p.stage)}`,`N2: ${present(d.n2Status)}${d.nodalConfirmationPlan?` · plan: ${d.nodalConfirmationPlan}`:''}`,`Biomarker status: ${present(d.biomarkerStatus)}${checked.length?` · checked: ${checked.join(', ')}`:''}`,`SBAR: ${present(snap.sbar)}`,`Medication safety: ${present(snap.medication)}`,`Patient update: ${present(snap.patientUpdate)}`,`Treatment intent: ${present(tc.intent)} · Fitness: ${present(tc.fitness)} · Resectability: ${present(tc.resectability)}`,`Driver: ${present(tc.driverStatus)}${tc.driverName?` · ${tc.driverName}`:''}`,`Guideline lane: ${present(tr.pathway?.title)}`,`Clinician decision: ${dec.selectedOptionId?dec.selectedOptionId:'Chưa lưu'}${ds.stale?' · STALE':''}`,`Decision rationale: ${present(dec.rationale)}`,`Guideline provenance: ${dec.sourceLabel?`${dec.sourceLabel} · ${present(dec.sourceUpdated)}`:'Chưa có decision provenance'}`,`MDT conclusion: ${present(d.mdtDecision)}`,`Patient-facing plan: ${present(d.plan)}`,`Safety note: Demo clinical decision support; no prescription/order is generated.`];return lines.join('\n')}
export function mdtPacketPanel(state){const d=state.doctorReview||{},tr=treatmentReadiness(state),ds=treatmentDecisionStatus(state),snap=clinicalSnapshot(state),decision=d.treatmentContext?.decision||{},readiness=[{label:'Pathology',ok:Boolean(d.diagnosisConfirmed&&d.pathologyReviewed)},{label:'TNM 9',ok:Boolean(d.stagingInput?.calculatedStage&&d.stagingReviewed)},{label:'Biomarker',ok:d.diseaseExtent!=='advanced'||d.biomarkerStatus==='complete'},{label:'Treatment routing',ok:tr.ready},{label:'Decision',ok:ds.exists&&!ds.stale},{label:'Safety',ok:!snap.urgent}];const ready=readiness.every(x=>x.ok);return `<section class="panel mdt-packet-panel"><div class="panel-head"><div><div class="eyebrow">MDT review packet</div><h2>One-page clinical handoff</h2></div><span class="state-chip ${ready?'':'warning'}">${ready?'Ready to review':'Needs review'}</span></div><div class="mdt-readiness">${readiness.map(x=>`<div class="${x.ok?'ok':'missing'}"><span>${x.ok?'✓':'!'}</span><b>${esc(x.label)}</b></div>`).join('')}</div>${snap.urgent?'<div class="impact-alert"><strong>Safety first</strong><span>Có red flag/urgent patient update; ưu tiên đánh giá an toàn trước hội chẩn thường quy.</span></div>':''}<div class="mdt-summary-grid"><div><span>Pathology</span><strong>${esc(d.pathologyReviewed?d.pathologyType:'Chưa review')}</strong></div><div><span>TNM</span><strong>${esc(state.patient?.tnm||'Chưa có')}</strong></div><div><span>Guideline lane</span><strong>${esc(tr.pathway?.title||'Chưa định tuyến')}</strong></div><div><span>Clinician decision</span><strong>${esc(decision.selectedOptionId||'Chưa lưu')}${ds.stale?' · STALE':''}</strong></div></div><div class="action-row"><button class="secondary-btn" data-action="copy-mdt-packet">Copy MDT packet</button></div><p class="helper-text">Packet chỉ tổng hợp dữ liệu đã có; không tự điền dữ liệu thiếu và không tạo y lệnh.</p></section>`}

if(typeof document!=='undefined')document.addEventListener('click',async event=>{const button=event.target.closest?.('[data-action="copy-mdt-packet"]');if(!button)return;event.preventDefault();event.stopImmediatePropagation();const root=button.closest('.workspace-shell');const packet=root?.querySelector('[data-mdt-packet-text]')?.dataset.mdtPacketText;if(packet){try{await navigator.clipboard.writeText(packet);button.textContent='Đã copy';setTimeout(()=>button.textContent='Copy MDT packet',1200)}catch{window.alert('Không thể copy trong trình duyệt này.')}}},true);
