const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=(v='')=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const active=s=>s?.cases?.find(x=>x.id===s.activeCaseId)||null;
const D=[['CN',0],['T2',1],['T3',2],['T4',3],['T5',4],['T6',5],['T7',6]];
function meds(c){const m=c.medicationToday||{};return {schedule:m.schedule||[],history:m.history||[]}}
function todayKey(){return new Date().toISOString().slice(0,10)}
function latestFor(history,id){return [...history].reverse().find(x=>x.medicationId===id&&x.date===todayKey())}
function currentTreatment(c){return c?.clinicalMonitoring?.currentTreatment||{}}
function seedFromTreatment(c){const m=meds(c);if(m.schedule.length)return m.schedule;const tx=currentTreatment(c);if(!tx.name)return[];return [{id:'tx-main',name:tx.name,time:'08:00',instructions:'Theo kế hoạch điều trị đã được team xác nhận.',daysOfWeek:[0,1,2,3,4,5,6],active:true}]}
function dueToday(x){return x.active!==false&&(!Array.isArray(x.daysOfWeek)||!x.daysOfWeek.length||x.daysOfWeek.includes(new Date().getDay()))}
function card(c){const m=meds(c),all=seedFromTreatment(c),schedule=all.filter(dueToday),history=m.history;return `<section class="med-today" data-med-today><div class="med-today-head"><div><div class="eyebrow">Medication Today</div><h2>Thuốc hôm nay</h2><p>Chỉ hiện thuốc được lên lịch cho đúng ngày hôm nay.</p></div><button class="secondary-btn" data-action="med-config">Cài ngày & giờ</button></div><div class="med-list">${schedule.length?schedule.map(x=>{const log=latestFor(history,x.id);return `<article class="med-row"><div class="med-time">${esc(x.time||'--:--')}</div><div class="med-main"><strong>${esc(x.name)}</strong><small>${esc(x.instructions||'')}</small>${log?`<span class="med-status ${esc(log.status)}">${log.status==='taken'?'Đã uống':'Bỏ liều'}</span>`:''}</div><div class="med-actions">${!log?`<button class="primary-btn" data-action="med-mark" data-id="${esc(x.id)}" data-status="taken">Đã uống</button><button class="secondary-btn" data-action="med-mark" data-id="${esc(x.id)}" data-status="missed">Bỏ liều</button>`:`<button class="text-btn" data-action="med-undo" data-id="${esc(x.id)}">Sửa</button>`}</div></article>`}).join(''):'<div class="empty-state">Hôm nay không có thuốc được lên lịch.</div>'}</div></section>`}
function config(c){const s=seedFromTreatment(c),x=s[0]||{};const days=Array.isArray(x.daysOfWeek)&&x.daysOfWeek.length?x.daysOfWeek:[0,1,2,3,4,5,6];return `<div class="med-modal" data-med-modal><div class="med-dialog"><div class="panel-head"><div><div class="eyebrow">Medication schedule</div><h2>Cài ngày uống thuốc</h2></div><button data-action="med-close">Đóng</button></div><label>Tên thuốc / điều trị<input id="medName" value="${esc(x.name||'')}"></label><label>Giờ nhắc<input id="medTime" type="time" value="${esc(x.time||'08:00')}"></label><div class="med-day-picks">${D.map(([l,v])=>`<label><input type="checkbox" data-med-day value="${v}" ${days.includes(v)?'checked':''}><span>${l}</span></label>`).join('')}</div><label>Hướng dẫn<textarea id="medInstructions">${esc(x.instructions||'Theo kế hoạch đã được team xác nhận.')}</textarea></label><div class="info-callout">Lịch này chỉ là nhắc dùng thuốc đã được xác nhận. Không tự đổi liều hoặc ngưng thuốc.</div><div class="action-row"><button class="primary-btn" data-action="med-save-config">Lưu lịch</button></div></div></div>`}
function inject(){const s=read(),c=active(s);if(!s||!c||s.activeRole!=='patient'||document.querySelector('[data-med-today]'))return;(document.querySelector('.patient-home')||document.querySelector('.patient-modern-card'))?.insertAdjacentHTML('afterbegin',card(c))}
function saveCase(s,c){const i=s.cases.findIndex(x=>x.id===c.id);if(i>=0){s.cases[i]=c;write(s)}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const s=read(),c=active(s);if(!s||!c)return;const a=b.dataset.action;if(a==='med-config'){e.preventDefault();document.body.insertAdjacentHTML('beforeend',config(c))}if(a==='med-close'){e.preventDefault();document.querySelector('[data-med-modal]')?.remove()}if(a==='med-save-config'){e.preventDefault();const name=document.getElementById('medName')?.value?.trim(),time=document.getElementById('medTime')?.value||'08:00',instructions=document.getElementById('medInstructions')?.value?.trim()||'',days=[...document.querySelectorAll('[data-med-day]:checked')].map(x=>Number(x.value));if(!name||!days.length)return;c.medicationToday=c.medicationToday||{};c.medicationToday.schedule=[{id:'custom-1',name,time,instructions,daysOfWeek:days,active:true}];c.events=[...(c.events||[]),{id:crypto.randomUUID(),type:'MEDICATION_SCHEDULE_CONFIGURED',role:'patient',text:`Đã cấu hình lịch thuốc ${name}.`,at:new Date().toISOString()}];saveCase(s,c);location.reload()}if(a==='med-mark'){e.preventDefault();const m=meds(c),schedule=seedFromTreatment(c),med=schedule.find(x=>x.id===b.dataset.id);if(!med)return;const status=b.dataset.status,now=new Date();c.medicationToday=c.medicationToday||{};c.medicationToday.schedule=schedule;c.medicationToday.history=[...(m.history||[]),{id:crypto.randomUUID(),medicationId:med.id,name:med.name,status,date:todayKey(),time:now.toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}),at:now.toISOString()}];if(status==='missed'){c.unreadAlerts=(c.unreadAlerts||0)+1;c.events=[...(c.events||[]),{id:crypto.randomUUID(),type:'PATIENT_MEDICATION_MISSED',role:'patient',text:`Bệnh nhân ghi nhận bỏ liều: ${med.name}.`,at:now.toISOString()}]}else c.events=[...(c.events||[]),{id:crypto.randomUUID(),type:'PATIENT_MEDICATION_TAKEN',role:'patient',text:`Bệnh nhân ghi nhận đã dùng thuốc: ${med.name}.`,at:now.toISOString()}];saveCase(s,c);location.reload()}if(a==='med-undo'){e.preventDefault();const hist=c.medicationToday?.history||[];const idx=[...hist].map((x,i)=>({x,i})).reverse().find(y=>y.x.medicationId===b.dataset.id&&y.x.date===todayKey())?.i;if(idx>=0)hist.splice(idx,1);c.medicationToday.history=hist;saveCase(s,c);location.reload()}},true);
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);