const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=(v='')=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const active=s=>s?.cases?.find(x=>x.id===s.activeCaseId)||null;
function panel(c){const x=c.newPatientIntake;if(!x||!['submitted','reviewing','verified'].includes(x.status))return'';const r=x.nurseReview||{};return `<section class="npi-nurse" data-npi-nurse><div class="panel-head"><div><div class="eyebrow">New patient intake</div><h2>Hồ sơ bệnh nhân gửi trước khám</h2></div><span class="state-chip">${x.status==='verified'?'Đã xác minh':x.status==='reviewing'?'Đang xác minh':'Mới gửi'}</span></div><div class="npi-review-summary"><div><span>Họ tên</span><strong>${esc(x.profile?.name||c.patient?.name||'')}</strong></div><div><span>Lý do khám</span><strong>${esc(x.chiefConcern||'Chưa khai')}</strong></div><div><span>Dị ứng tự khai</span><strong>${esc(x.allergySelfReport||'unknown')}</strong></div><div><span>Tài liệu</span><strong>${(x.attachments||[]).length} tệp</strong></div></div><div class="npi-review-grid"><label class="check-card"><input id="npiIdentityVerified" type="checkbox" ${r.identityVerified?'checked':''}><span><strong>Đã xác minh danh tính</strong><small>Đối chiếu theo quy trình cơ sở; ảnh CCCD chỉ là tài liệu hỗ trợ demo.</small></span></label><label class="check-card"><input id="npiMedsReviewed" type="checkbox" ${r.medicationsReviewed?'checked':''}><span><strong>Đã đối chiếu thuốc đang dùng</strong><small>Hỏi lại tên thuốc, cách dùng nếu thông tin bệnh nhân chưa rõ.</small></span></label><label>Dị ứng thuốc<select id="npiAllergyStatus"><option value="unknown" ${r.allergyStatus==='unknown'?'selected':''}>Chưa xác định</option><option value="none" ${r.allergyStatus==='none'?'selected':''}>Chưa ghi nhận dị ứng</option><option value="confirmed" ${r.allergyStatus==='confirmed'?'selected':''}>Có dị ứng đã xác nhận</option></select></label><label>Chi tiết dị ứng<textarea id="npiAllergyVerifiedNote">${esc(r.allergyNote||x.allergyNote||'')}</textarea></label><label class="full">Ghi chú xác minh / điều cần bác sĩ chú ý<textarea id="npiNurseNote">${esc(r.note||'')}</textarea></label></div><div class="action-row"><button class="secondary-btn" data-action="npi-nurse-save">Lưu đang xác minh</button><button class="primary-btn" data-action="npi-nurse-verify">Xác minh & chuyển bước bác sĩ</button></div></section>`}
function inject(){const s=read(),c=active(s);if(!s||!c||s.activeRole!=='nurse'||document.querySelector('[data-npi-nurse]'))return;const html=panel(c);if(!html)return;const root=document.querySelector('.nurse-layout .stack');root?.insertAdjacentHTML('afterbegin',html)}
function saveReview(verify){const s=read(),c=active(s);if(!s||!c?.newPatientIntake)return;const x=c.newPatientIntake,now=new Date().toISOString(),review={identityVerified:Boolean(document.getElementById('npiIdentityVerified')?.checked),medicationsReviewed:Boolean(document.getElementById('npiMedsReviewed')?.checked),allergyStatus:document.getElementById('npiAllergyStatus')?.value||'unknown',allergyNote:document.getElementById('npiAllergyVerifiedNote')?.value.trim()||'',note:document.getElementById('npiNurseNote')?.value.trim()||'',reviewedAt:now};if(verify&&(!review.identityVerified||!review.medicationsReviewed||review.allergyStatus==='unknown'))return alert('Cần xác minh danh tính, thuốc đang dùng và trạng thái dị ứng trước khi chuyển bác sĩ.');x.nurseReview=review;x.status=verify?'verified':'reviewing';if(verify){c.intake=c.intake||{};c.intake.medicationSafety=c.intake.medicationSafety||{};c.intake.medicationSafety.allergiesReviewed=true;c.intake.medicationSafety.medicationsReviewed=true;c.intake.medicationSafety.allergies=review.allergyStatus==='none'?'Chưa ghi nhận dị ứng':review.allergyNote;c.intake.medicationSafety.currentMedications=x.medications||c.intake.medicationSafety.currentMedications||''}c.events=[...(c.events||[]),{id:crypto.randomUUID(),type:verify?'NEW_PATIENT_INTAKE_VERIFIED':'NEW_PATIENT_INTAKE_REVIEW_STARTED',role:'nurse',text:verify?'Điều dưỡng đã xác minh hồ sơ bệnh nhân mới và chuyển bước bác sĩ.':'Điều dưỡng đang xác minh hồ sơ bệnh nhân mới.',at:now}];const i=s.cases.findIndex(k=>k.id===c.id);s.cases[i]=c;write(s);location.reload()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='npi-nurse-save'){e.preventDefault();saveReview(false)}if(b.dataset.action==='npi-nurse-verify'){e.preventDefault();saveReview(true)}},true);
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);