const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=(v='')=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function pending(s){return (s?.cases||[]).filter(c=>['submitted','reviewing'].includes(c?.newPatientIntake?.status))}
function active(s){return s?.cases?.find(c=>c.id===s.activeCaseId)||null}
function queue(s){const rows=pending(s);return `<section class="npi-queue" data-npi-queue><div class="panel-head"><div><div class="eyebrow">New patient queue</div><h2>Bệnh nhân mới chờ xác minh</h2></div><span class="state-chip">${rows.length} ca</span></div>${rows.length?`<div class="npi-queue-list">${rows.map(c=>{const x=c.newPatientIntake,a=(x.attachments||[]).length;return `<button data-action="npi-open-case" data-case="${esc(c.id)}"><div><strong>${esc(x.profile?.name||c.patient?.name||'Bệnh nhân')}</strong><span>${esc(x.chiefConcern||'Chưa mô tả lý do khám')}</span></div><div><b>${x.status==='reviewing'?'Đang xác minh':'Mới gửi'}</b><small>${a} tài liệu</small></div></button>`}).join('')}</div>`:'<div class="empty-state">Không có bệnh nhân mới đang chờ xác minh.</div>'}</section>`}
function gate(c){const x=c?.newPatientIntake;if(!x||x.status==='verified')return'';return `<section class="doctor-intake-gate" data-doctor-intake-gate><div><div class="eyebrow">Chưa đủ điều kiện khám</div><h2>Hồ sơ bệnh nhân mới chưa được Nurse xác minh</h2><p>Bác sĩ chỉ mở workflow lâm sàng sau khi điều dưỡng đã xác minh định danh, thuốc đang dùng và trạng thái dị ứng.</p></div><div class="gate-steps"><span class="done">Patient đã khai</span><span class="${x.status==='reviewing'?'active':''}">Nurse xác minh</span><span>Bác sĩ khám</span></div></section>`}
function inject(){const s=read(),c=active(s);if(!s||!c)return;if(s.activeRole==='nurse'&&!document.querySelector('[data-npi-queue]')){const root=document.querySelector('.nurse-layout .stack');root?.insertAdjacentHTML('afterbegin',queue(s))}if(s.activeRole==='doctor'&&!document.querySelector('[data-doctor-intake-gate]')){const html=gate(c);if(!html)return;const root=document.querySelector('.doctor-layout')||document.querySelector('.workspace');if(root){root.insertAdjacentHTML('afterbegin',html);root.classList.add('doctor-gated')}}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action="npi-open-case"]');if(!b)return;const s=read();if(!s)return;s.activeCaseId=b.dataset.case;write(s);location.reload()},true);
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);