const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=(v='')=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const active=s=>s?.cases?.find(x=>x.id===s.activeCaseId)||null;
const severe=t=>['fatigue','nausea','diarrhea','skin','neuropathy'].some(k=>t?.[k]==='severe')||t?.adherence==='stopped';
function queueFor(c){const q=[];for(const t of c.urgentTriage||[]){if(t.status!=='closed')q.push({id:t.id,type:'urgent',priority:0,status:t.status==='in_progress'?'reviewing':'new',title:`Urgent call · ${t.reason}`,detail:t.note||'Bệnh nhân yêu cầu team gọi lại',at:t.requestedAt})}const tox=c.patientTracking?.toxicity||{};if(tox.updatedAt&&severe(tox))q.push({id:'toxicity',type:'toxicity',priority:1,status:c.nurseTriage?.toxicityStatus||'new',title:'Độc tính / adherence cần review',detail:tox.note||tox.adherence||'',at:tox.updatedAt});const p=c.patientTracking?.previsit||{};if(p.updatedAt)q.push({id:'previsit',type:'previsit',priority:3,status:c.nurseTriage?.previsitStatus||'new',title:'Pre-visit mới',detail:p.concern||p.change||'Bệnh nhân đã cập nhật trước khám',at:p.updatedAt});const last=[...(c.patientTracking?.checkins||[])].reverse()[0];if(last?.at)q.push({id:'symptom',type:'symptom',priority:last?.report&&(last.report.hemoptysis||last.report.confusion||last.report.chestPain||last.report.dyspnea==='Tăng nhiều')?0:2,status:c.nurseTriage?.symptomStatus||'new',title:'Symptom check-in',detail:last.summary||'Có cập nhật triệu chứng mới',at:last.at});return q.sort((a,b)=>a.priority-b.priority||new Date(b.at||0)-new Date(a.at||0))}
function counts(q){return{new:q.filter(x=>x.status==='new').length,reviewing:q.filter(x=>x.status==='reviewing').length,escalated:q.filter(x=>x.status==='escalated').length,resolved:q.filter(x=>x.status==='resolved').length}}
function panel(c){const q=queueFor(c),n=counts(q);return `<section class="nurse-command" data-nurse-command><div class="nurse-command-head"><div><div class="eyebrow">Nurse triage command center</div><h2>Hàng đợi cần xử lý</h2><p>Ưu tiên urgent call, độc tính và symptom mới trước workflow thường quy.</p></div><div class="triage-counts"><span><b>${n.new}</b> New</span><span><b>${n.reviewing}</b> Reviewing</span><span><b>${n.escalated}</b> Escalated</span><span><b>${n.resolved}</b> Resolved</span></div></div><div class="triage-queue">${q.length?q.map(x=>`<article class="triage-item p${x.priority}"><div><span>${esc(x.type)}</span><strong>${esc(x.title)}</strong><small>${esc(x.detail||'')}</small></div><div class="triage-item-side"><em>${esc(x.status)}</em><button data-action="nurse-open-triage" data-id="${esc(x.id)}" data-type="${esc(x.type)}">Mở</button></div></article>`).join(''):'<div class="empty-state">Không có item mới cần triage.</div>'}</div></section>`}
function detail(c,id,type){const tx=c.clinicalMonitoring?.currentTreatment||{},tox=c.patientTracking?.toxicity||{},p=c.patientTracking?.previsit||{},last=[...(c.patientTracking?.checkins||[])].reverse()[0],u=(c.urgentTriage||[]).find(x=>x.id===id);const body=type==='urgent'?`${u?.reason||''} — ${u?.note||''}`:type==='toxicity'?`${tox.note||''} · adherence ${tox.adherence||'—'}`:type==='previsit'?`${p.concern||''} ${p.change||''}`:`${last?.summary||''}`;return `<div class="nurse-triage-modal" data-nurse-triage-modal><div class="nurse-triage-dialog"><div class="panel-head"><div><div class="eyebrow">Triage review</div><h2>${esc(type)}</h2></div><button data-action="nurse-close-triage">Đóng</button></div><div class="triage-context-grid"><div><span>Điều trị hiện tại</span><strong>${esc(tx.name||'Chưa ghi')}</strong><small>${esc(tx.cycle||'')}</small></div><div><span>Adherence</span><strong>${esc(tox.adherence||'Chưa cập nhật')}</strong><small>${severe(tox)?'Có tín hiệu nặng':'Chưa ghi nhận nặng'}</small></div><div><span>Patient signal</span><strong>${esc(body||'Chưa có chi tiết')}</strong></div></div><div class="verify-list"><label><input id="verifyIdentity" type="checkbox"> Xác minh danh tính / người gọi</label><label><input id="verifySymptoms" type="checkbox"> Xác minh symptom & thời điểm khởi phát</label><label><input id="verifyMeds" type="checkbox"> Đối chiếu thuốc đang dùng / liều gần nhất</label><label><input id="verifyRedFlags" type="checkbox"> Hỏi red flags cần escalation</label></div><label>Ghi chú điều dưỡng<textarea id="nurseTriageNote"></textarea></label><label>Trạng thái<select id="nurseTriageStatus"><option value="reviewing">Reviewing</option><option value="escalated">Escalated</option><option value="resolved">Resolved</option></select></label><div class="urgent-actions"><button class="primary-btn" data-action="nurse-save-triage" data-id="${esc(id)}" data-type="${esc(type)}">Lưu cập nhật</button></div><p class="helper-text">Điều dưỡng xác minh và điều phối; quyết định điều trị thuộc clinician có thẩm quyền.</p></div></div>`}
function inject(){const s=read(),c=active(s),root=document.querySelector('.workspace');if(!s||!c||s.activeRole!=='nurse'||!root||document.querySelector('[data-nurse-command]'))return;const marker=root.querySelector('.patient-strip')||root.querySelector('.workspace-title');marker?.insertAdjacentHTML('afterend',panel(c))}
function upsertEscalation(c,type,id,note,verification){c.nurseEscalations=c.nurseEscalations||[];const key=`${type}:${id}`,now=new Date().toISOString(),existing=c.nurseEscalations.find(x=>x.key===key&&x.status!=='resolved');const payload={key,sourceType:type,sourceId:id,note,verification,escalatedAt:existing?.escalatedAt||now,updatedAt:now,status:'open',doctorAckAt:existing?.doctorAckAt||null,doctorResolvedAt:null,doctorNote:existing?.doctorNote||''};if(existing)Object.assign(existing,payload);else c.nurseEscalations.push({id:crypto.randomUUID(),...payload})}
function setStatus(c,type,id,status,note,verification){c.nurseTriage=c.nurseTriage||{};if(type==='toxicity')c.nurseTriage.toxicityStatus=status;if(type==='previsit')c.nurseTriage.previsitStatus=status;if(type==='symptom')c.nurseTriage.symptomStatus=status;if(type==='urgent'){const u=(c.urgentTriage||[]).find(x=>x.id===id);if(u)u.status=status==='resolved'?'closed':status==='reviewing'?'in_progress':'waiting'}if(status==='escalated')upsertEscalation(c,type,id,note,verification);c.events=[...(c.events||[]),{id:crypto.randomUUID(),type:status==='escalated'?'NURSE_ESCALATED_TO_DOCTOR':'NURSE_TRIAGE_UPDATED',role:'nurse',text:`Triage ${type}: ${status}${note?` — ${note}`:''}.`,at:new Date().toISOString()}]}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,s=read(),c=active(s);if(!s||!c)return;if(a==='nurse-open-triage'){e.preventDefault();document.body.insertAdjacentHTML('beforeend',detail(c,b.dataset.id,b.dataset.type))}if(a==='nurse-close-triage'){e.preventDefault();document.querySelector('[data-nurse-triage-modal]')?.remove()}if(a==='nurse-save-triage'){e.preventDefault();const status=document.getElementById('nurseTriageStatus')?.value||'reviewing',note=document.getElementById('nurseTriageNote')?.value?.trim()||'',verification={identity:Boolean(document.getElementById('verifyIdentity')?.checked),symptoms:Boolean(document.getElementById('verifySymptoms')?.checked),meds:Boolean(document.getElementById('verifyMeds')?.checked),redFlags:Boolean(document.getElementById('verifyRedFlags')?.checked)};setStatus(c,b.dataset.type,b.dataset.id,status,note,verification);const i=s.cases.findIndex(x=>x.id===c.id);s.cases[i]=c;write(s);location.reload()}},true);
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);
