const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const esc=(v='')=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const active=s=>s?.cases?.find(x=>x.id===s.activeCaseId)||null;
const DAY=['CN','T2','T3','T4','T5','T6','T7'];
function toxLevel(c){const t=c?.patientTracking?.toxicity||{};const vals=['fatigue','nausea','diarrhea','skin','neuropathy'].map(k=>t[k]);if(vals.includes('severe'))return{level:'danger',title:'Độc tính nặng',text:'Có triệu chứng mức nặng đã được ghi nhận. Liên hệ team điều trị; nếu xấu nhanh dùng hỗ trợ khẩn cấp.'};if(vals.includes('moderate'))return{level:'warn',title:'Độc tính cần theo dõi',text:'Có triệu chứng mức vừa. Cập nhật lại hôm nay và báo team nếu tăng.'};return{level:'ok',title:'Chưa có cảnh báo độc tính nặng',text:'Tiếp tục check-in tác dụng phụ theo kế hoạch.'}}
function upcoming(c){const now=Date.now();return (c?.sharedCarePlan?.actions||[]).filter(x=>x.status!=='completed'&&x.dueAt&&new Date(x.dueAt).getTime()>=now).sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt))[0]||null}
function countdown(d){if(!d)return'';const ms=new Date(d).getTime()-Date.now(),days=Math.ceil(ms/86400000);if(days<=0)return'Hôm nay';if(days===1)return'Còn 1 ngày';return`Còn ${days} ngày`}
function kindLabel(x){const k=x?.type||'';return {appointment:'Tái khám',imaging:'CT / hình ảnh',lab:'Xét nghiệm',callback:'Gọi lại',monitoring:'Theo dõi'}[k]||'Mốc chăm sóc'}
function week(c){const m=c?.medicationToday||{},schedule=m.schedule||[],history=m.history||[];const today=new Date();return Array.from({length:7},(_,i)=>{const d=new Date(today);d.setDate(today.getDate()+i);const key=d.toISOString().slice(0,10),dow=d.getDay();const due=schedule.filter(x=>x.active!==false&&(!Array.isArray(x.daysOfWeek)||!x.daysOfWeek.length||x.daysOfWeek.includes(dow)));const done=history.filter(h=>h.date===key&&h.status==='taken').length;return {key,label:DAY[dow],day:d.getDate(),due:due.length,done,isToday:i===0}})}
function panel(c){const tox=toxLevel(c),next=upcoming(c),days=week(c);return `<section class="patient-daily-hub" data-patient-daily-hub><div class="daily-top"><div><div class="eyebrow">Hôm nay</div><h2>Lịch điều trị của bạn</h2></div>${next?`<div class="next-countdown"><span>${esc(kindLabel(next))}</span><strong>${esc(countdown(next.dueAt))}</strong><small>${new Date(next.dueAt).toLocaleString('vi-VN')}</small></div>`:'<div class="next-countdown muted"><span>Lịch sắp tới</span><strong>Chưa có mốc</strong><small>Team sẽ cập nhật tái khám / CT / xét nghiệm.</small></div>'}</div><div class="med-week">${days.map(d=>`<div class="med-day ${d.isToday?'today':''}"><span>${d.label}</span><strong>${d.day}</strong><small>${d.due?`${d.done}/${d.due} liều`:'Không có thuốc'}</small></div>`).join('')}</div><div class="tox-banner ${tox.level}"><div><strong>${esc(tox.title)}</strong><span>${esc(tox.text)}</span></div><button data-action="patient-step" data-step="toxicity">Check-in độc tính</button></div>${next?`<div class="next-care-card"><div><span>${esc(kindLabel(next))}</span><strong>${esc(next.title)}</strong><small>${esc(next.note||'')}</small></div><b>${esc(countdown(next.dueAt))}</b></div>`:''}</section>`}
function inject(){const s=read(),c=active(s);if(!s||!c||s.activeRole!=='patient'||document.querySelector('[data-patient-daily-hub]'))return;const root=document.querySelector('.patient-home');root?.insertAdjacentHTML('afterbegin',panel(c))}
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);