const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const v=id=>document.getElementById(id)?.value??'';
const c=id=>Boolean(document.getElementById(id)?.checked);
const num=id=>{const x=v(id);return x===''?'':Number(x)};
function activeIndex(state){return state?.cases?.findIndex(x=>x.id===state.activeCaseId)??-1}
function event(type,text,role='patient'){return{id:crypto.randomUUID(),type,role,text,at:new Date().toISOString()}}
async function media(id,kind){const f=document.getElementById(id)?.files?.[0];if(!f)return null;const allowed=kind==='photo'?['image/jpeg','image/png','image/webp']:['audio/mpeg','audio/wav','audio/webm','audio/mp4'];if(!allowed.includes(f.type))throw new Error(`${kind==='photo'?'Ảnh':'Voice'} demo chỉ nhận định dạng an toàn phổ biến.`);if(f.size>650000)throw new Error(`${kind==='photo'?'Ảnh':'Voice'} demo tối đa khoảng 650 KB.`);return await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({kind,name:f.name,type:f.type,size:f.size,dataUrl:r.result});r.onerror=reject;r.readAsDataURL(f)})}
function saveCase(state,idx,next){state.cases[idx]=next;write(state);location.reload()}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(!['save-previsit','save-toxicity','save-symptom-checkin'].includes(a))return;e.preventDefault();e.stopPropagation();const state=read(),idx=activeIndex(state);if(idx<0)return alert('Không tìm thấy ca hiện tại.');const current=state.cases[idx],tracking=current.patientTracking||{previsit:{},toxicity:{},checkins:[]};if(a==='save-previsit'){const now=new Date().toISOString(),previsit={type:v('previsitType'),activity:v('previsitActivity'),weight:num('previsitWeight'),appetite:v('previsitAppetite'),concern:v('previsitConcern').trim(),change:v('previsitChange').trim(),updatedAt:now};const next={...current,patientTracking:{...tracking,previsit},unreadAlerts:(current.unreadAlerts||0)+1,events:[...(current.events||[]),event('PATIENT_PREVISIT_UPDATED','Bệnh nhân đã hoàn tất khai trước khám; team có dữ liệu mới để review.')]};return saveCase(state,idx,next)}if(a==='save-toxicity'){const now=new Date().toISOString(),toxicity={adherence:v('toxAdherence'),fatigue:v('toxFatigue'),nausea:v('toxNausea'),diarrhea:v('toxDiarrhea'),skin:v('toxSkin'),neuropathy:v('toxNeuropathy'),note:v('toxNote').trim(),updatedAt:now},severe=['fatigue','nausea','diarrhea','skin','neuropathy'].some(k=>toxicity[k]==='severe')||toxicity.adherence==='stopped';const next={...current,patientTracking:{...tracking,toxicity},unreadAlerts:(current.unreadAlerts||0)+(severe?1:0),events:[...(current.events||[]),event(severe?'PATIENT_TOXICITY_ALERT':'PATIENT_TOXICITY_UPDATED',severe?'Bệnh nhân báo độc tính/thuốc cần team ưu tiên review.':'Bệnh nhân cập nhật theo dõi thuốc và độc tính.') ]};return saveCase(state,idx,next)}if(a==='save-symptom-checkin'){try{const photo=await media('trackPhoto','photo'),voice=await media('trackVoice','voice'),now=new Date().toISOString(),report={dyspnea:v('trackDyspnea'),pain:num('trackPain'),fever:c('trackFever'),hemoptysis:c('trackHemoptysis'),confusion:c('trackConfusion'),chestPain:c('trackChestPain'),note:v('trackSymptomNote').trim(),submittedAt:now},urgent=report.hemoptysis||report.confusion||report.chestPain||report.dyspnea==='Tăng nhiều',checkin={id:crypto.randomUUID(),kind:'symptom',at:now,summary:`Khó thở: ${report.dyspnea}; đau ${report.pain===''?'chưa ghi':report.pain}/10`,report,attachments:[photo,voice].filter(Boolean)};const next={...current,unreadAlerts:(current.unreadAlerts||0)+(urgent?1:0),patientEducation:{...current.patientEducation,symptomReport:report},patientTracking:{...tracking,checkins:[...(tracking.checkins||[]),checkin]},events:[...(current.events||[]),event(urgent?'PATIENT_URGENT_SYMPTOM':'PATIENT_SYMPTOM_UPDATE',urgent?'Bệnh nhân gửi triệu chứng cảnh báo kèm dữ liệu theo dõi; team cần ưu tiên review.':'Bệnh nhân gửi symptom check-in mới.')]};return saveCase(state,idx,next)}catch(err){return alert(err.message||'Không thể lưu media.')}}},true);
