const KEY='lungcare.phase1.state';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=(v='')=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const active=s=>s?.cases?.find(x=>x.id===s.activeCaseId)||null;
const actions=c=>c?.sharedCarePlan?.actions||[];
const roleLabel=r=>({patient:'Patient',nurse:'Nurse',doctor:'Doctor'}[r]||r);
const typeLabel=t=>({appointment:'Tái khám',imaging:'CT / hình ảnh',lab:'Xét nghiệm',callback:'Gọi lại',monitoring:'Theo dõi'}[t]||'Care action');
function panel(c,role){const items=actions(c);return `<section class="shared-care-plan" data-shared-care-plan><div class="care-plan-head"><div><div class="eyebrow">Shared care plan</div><h2>Việc cần làm tiếp theo</h2><p>Điều phối Patient · Nurse · Doctor sau triage/escalation. Không phải order set.</p></div>${role==='doctor'?'<button class="primary-btn" data-action="care-add">+ Thêm action</button>':''}</div><div class="care-action-list">${items.length?items.slice().reverse().map(x=>`<article class="care-action ${esc(x.status)}"><div><span>${esc(typeLabel(x.type))} · ${esc(roleLabel(x.owner))}</span><strong>${esc(x.title)}</strong><small>${esc(x.note||'')}</small><em>${x.dueAt?`Mốc: ${new Date(x.dueAt).toLocaleString('vi-VN')}`:'Chưa đặt mốc'}</em></div><div class="care-action-side"><b>${esc(x.status)}</b>${x.status!=='completed'&&x.owner===role?`<button data-action="care-complete" data-id="${esc(x.id)}">Đánh dấu xong</button>`:''}</div></article>`).join(''):'<div class="empty-state">Chưa có shared care action.</div>'}</div></section>`}
function modal(){return `<div class="care-plan-modal" data-care-modal><div class="care-plan-dialog"><div class="panel-head"><div><div class="eyebrow">Create care action</div><h2>Thêm việc cần phối hợp</h2></div><button data-action="care-close">Đóng</button></div><label>Loại mốc<select id="careType"><option value="appointment">Tái khám</option><option value="imaging">CT / hình ảnh</option><option value="lab">Xét nghiệm</option><option value="callback">Gọi lại</option><option value="monitoring">Theo dõi</option></select></label><label>Người phụ trách<select id="careOwner"><option value="patient">Patient</option><option value="nurse">Nurse</option><option value="doctor">Doctor</option></select></label><label>Việc cần làm<input id="careTitle" placeholder="VD: Tái khám bác sĩ ung bướu"></label><label>Chi tiết<textarea id="careNote" placeholder="Chuẩn bị gì, khi nào đến, điều gì cần theo dõi..."></textarea></label><label>Ngày giờ<input id="careDue" type="datetime-local"></label><div class="critical-alert"><strong>Không nhập y lệnh, liều thuốc hay thay đổi điều trị vào đây. Action này chỉ dùng cho care coordination.</strong></div><div class="urgent-actions"><button class="primary-btn" data-action="care-save">Lưu action</button></div></div></div>`}
function inject(){const s=read(),c=active(s),root=document.querySelector('.workspace');if(!s||!c||!['doctor','nurse','patient'].includes(s.activeRole)||!root||document.querySelector('[data-shared-care-plan]'))return;const marker=root.querySelector('[data-care-passport]')||root.querySelector('.patient-strip')||root.querySelector('.workspace-title');marker?.insertAdjacentHTML('afterend',panel(c,s.activeRole))}
function saveCase(s,c){const i=s.cases.findIndex(x=>x.id===c.id);if(i>=0){s.cases[i]=c;write(s)}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,s=read(),c=active(s);if(!s||!c)return;if(a==='care-add'){e.preventDefault();document.body.insertAdjacentHTML('beforeend',modal())}if(a==='care-close'){e.preventDefault();document.querySelector('[data-care-modal]')?.remove()}if(a==='care-save'){e.preventDefault();const type=document.getElementById('careType')?.value||'monitoring',owner=document.getElementById('careOwner')?.value||'patient',title=document.getElementById('careTitle')?.value?.trim()||'',note=document.getElementById('careNote')?.value?.trim()||'',due=document.getElementById('careDue')?.value;if(!title)return;const now=new Date().toISOString();const item={id:crypto.randomUUID(),type,owner,title,note,dueAt:due?new Date(due).toISOString():null,status:'open',createdAt:now,createdBy:s.activeRole,completedAt:null};c.sharedCarePlan=c.sharedCarePlan||{actions:[]};c.sharedCarePlan.actions=[...(c.sharedCarePlan.actions||[]),item];c.events=[...(c.events||[]),{id:crypto.randomUUID(),type:'CARE_ACTION_CREATED',role:s.activeRole,text:`${typeLabel(type)} cho ${owner}: ${title}.`,at:now}];if(owner!=='doctor')c.unreadAlerts=(c.unreadAlerts||0)+1;saveCase(s,c);location.reload()}if(a==='care-complete'){e.preventDefault();const item=actions(c).find(x=>x.id===b.dataset.id);if(!item)return;item.status='completed';item.completedAt=new Date().toISOString();c.events=[...(c.events||[]),{id:crypto.randomUUID(),type:'CARE_ACTION_COMPLETED',role:s.activeRole,text:`Hoàn tất care action: ${item.title}.`,at:item.completedAt}];saveCase(s,c);location.reload()}},true);
new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});queueMicrotask(inject);